# config/_default/menus.toml

[[main]]
name = "Top"
url = "/"
weight = -200

[[main]]
name = "Origins"
url = "/origins/"
weight = -100

[[main]]
name = "Browser"
url = "/browser/"
weight = 10

[[main]]
name = "IDE"
url = "/ide/"
weight = 10

[[main]]
name = "Playground"
url = "/playgrouds/"
weight = 10

[[main]]
name = "Singles"
url = "/singles/"
weight = 10

[[footer]]
name = "p.p."
url = "/privacypolicy"
